// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6r5P-0OwdEHAXlVK3NGHA1wkqsLNsWAo',
    appId: '1:1034758976128:web:7deaf91294dcda23be6c65',
    messagingSenderId: '1034758976128',
    projectId: 'catapp-da37a',
    authDomain: 'catapp-da37a.firebaseapp.com',
    storageBucket: 'catapp-da37a.appspot.com',
    measurementId: 'G-SEK7XMXT6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG8kjZ2SoaZSXY_gN29v98T43eAUAQCg0',
    appId: '1:1034758976128:android:d0bd0fac944e1df5be6c65',
    messagingSenderId: '1034758976128',
    projectId: 'catapp-da37a',
    storageBucket: 'catapp-da37a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTo8yXsOwsvHSS0eVRHuCOtWWkwhCHJTE',
    appId: '1:1034758976128:ios:69581a3e22520d88be6c65',
    messagingSenderId: '1034758976128',
    projectId: 'catapp-da37a',
    storageBucket: 'catapp-da37a.appspot.com',
    androidClientId: '1034758976128-519ot6vouehhkh62qpaveqnn8n9ljq9r.apps.googleusercontent.com',
    iosClientId: '1034758976128-k3skqoe8mk7fvm9u2lst548ojjv35i40.apps.googleusercontent.com',
    iosBundleId: 'com.example.catApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTo8yXsOwsvHSS0eVRHuCOtWWkwhCHJTE',
    appId: '1:1034758976128:ios:69581a3e22520d88be6c65',
    messagingSenderId: '1034758976128',
    projectId: 'catapp-da37a',
    storageBucket: 'catapp-da37a.appspot.com',
    androidClientId: '1034758976128-519ot6vouehhkh62qpaveqnn8n9ljq9r.apps.googleusercontent.com',
    iosClientId: '1034758976128-k3skqoe8mk7fvm9u2lst548ojjv35i40.apps.googleusercontent.com',
    iosBundleId: 'com.example.catApp',
  );
}
